### ISSUE TITLE
是不是现在已经不能用了？

### ISSUE THREAD

**Issue by sj8023ld** [Justson/DingDingHelper#12]
测试了一下，钉钉会提示不要使用模拟位置类软件，是不是这条路走不通了啊

**Comment by cnsunfocus** [comment]
什么情况,刚想试试呢

**Comment by JasonJunJun** [comment]
我有一个更简单的办法，[如何使用多余的手机实现钉钉自动打卡](http://45.77.124.228/2018/07/15/dingtalk-auto-clock-in/)
