### ISSUE TITLE
到工作页面就不动了，现在钉钉改哪了导致跑不动了，呼叫作者

### ISSUE THREAD

**Issue by helloworld10010** [Justson/DingDingHelper#13]

**Comment by helloworld10010** [comment]
刚才dubug了一会，原因是这个id找不到啊

/*工作页面的RecyclerView id*/
	private static final String RECYCLERVIEW_WORK_ID = "com.alibaba.android.rimet:id/oa_fragment_gridview";

**Comment by AlexMasky** [comment]
> 刚才dubug了一会，原因是这个id找不到啊
> 
> /_工作页面的RecyclerView id_/
> private static final String RECYCLERVIEW_WORK_ID = "com.alibaba.android.rimet:id/oa_fragment_gridview";

后来您解决问题了吗？我这边也是到工作页面就不动了。

**Comment by helloworld10010** [comment]
> > 刚才dubug了一会，原因是这个id找不到啊
> > /_工作页面的RecyclerView id_/
> > private static final String RECYCLERVIEW_WORK_ID = "com.alibaba.android.rimet:id/oa_fragment_gridview";
> 
> 后来您解决问题了吗？我这边也是到工作页面就不动了。

时间久了。具体我也忘了。  原因应该是他们界面改成H5的了。查不到控件。可以用绝对位置搞？但是可靠性太差

**Comment by Justson** [comment]
已更新
