### ISSUE TITLE
哇塞，我也正有此意做一个打卡的，每天迟到那么几分钟不划算

### ISSUE THREAD

**Issue by bbbBBBSG** [Justson/DingDingHelper#14]
哇塞，我也正有此意做一个打卡的，每天迟到那么几分钟不划算，有没有大佬说下什么型号的手机能root啊，一直没有成功过

**Comment by JasonJunJun** [comment]
我有一个更简单的办法，[如何使用多余的手机实现钉钉自动打卡](http://45.77.124.228/2018/07/15/dingtalk-auto-clock-in/)

**Comment by XXMY** [comment]
> 哇塞，我也正有此意做一个打卡的，每天迟到那么几分钟不划算，有没有大佬说下什么型号的手机能root啊，一直没有成功过

魅族手机自带root功能，一键重启即可
