### ISSUE TITLE
好像不能用吧？

### ISSUE THREAD

**Issue by hyr0318** [Justson/DingDingHelper#6]
到时间了 启动了钉钉，就没有反应了

**Comment by Justson** [comment]
可用。
* 对钉钉版本有要求。
*  检查Root是否完整，保证 am input 等命令能正确运行。

**Comment by AlexMasky** [comment]
> 可用。
> 
> * 对钉钉版本有要求。
> * 检查Root是否完整，保证 am input 等命令能正确运行。

请问您，是哪一个版本的钉钉呢？
